language: ruby
sudo: false
script: "bundle exec rake"
# Per https://github.com/travis-ci/travis-ci/issues/2821
install:
  - bundle install --retry=3
env:
  - DB=sqlite3
  - DB=postgres
  - DB=mysql
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - rbx-2
  # - jruby-19mode
notifications:
  webhooks:
    - https://webhooks.gitter.im/e/40dc875af26f64f39090
